### ISSUE TITLE
如何能得到L？

### ISSUE THREAD

**Issue by mzy2240** [gnijuohz/echarts-leaflet#12]
您好 现在通过 this.chart.getModel().getComponent('leaflet').__map 我已经能得到_map，请问如何能得到L，用来绘制另一层geojson数据。谢谢！！！！！

**Comment by gnijuohz** [comment]
不好意思前一段时间有点忙~

你是怎么用这个lib的，直接引入L不可以么?

**Comment by mzy2240** [comment]
没事 我已经转战使用supermap了 可能原理是一样的
