### ISSUE TITLE
does not match the corresponding path on disk `Leaflet.js`

### ISSUE THREAD

**Issue by harunkelesoglu** [gnijuohz/echarts-leaflet#13]
Hi,
I am trying use this library on react.But i get error the following error:
```bash
Module not found: `/Users/admin/Projects/DashboardBootstrap/node_modules/leaflet/src/leaflet.js` does not match the corresponding path on disk `Leaflet.js`.
```

I've detected the cause of the error. echarts-leaflet is imported from leaflet library as leaft/src/leaflet if you can update to echarts-leaflet.js file as follows it is fixed this error for react-scripts.
```javascript
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('echarts/lib/echarts'), require('leaflet/src/Leaflet')) :
```

**Comment by Poyoman39** [comment]
You can run `npm i https://github.com/Poyoman39/echarts-leaflet.git`if you can't wait the pull request to be merged

**Comment by harunkelesoglu** [comment]
Thanks @Poyoman39 . I done it different way. I wrote npm scripts and then added build and start.
`  "scripts": {
    "build-css": "node-sass-chokidar --include-path ./src --incle-path ./node_modules src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "start": "npm run fixed && npm-run-all -p watch-css start-js",
    "fixed":"mv ./node_modules/leaflet/src/Leaflet.js ./node_modules/leaflet/src/leaflet.js",
    "build": "npm run build-css && npm run fixed && REACT_APP_ENV=production react-scripts build"
  }`

**Comment by gnijuohz** [comment]
@harunkelesoglu @Poyoman39 's change has been merged I'll release a new version of this library soon. Thanks for reporting this issue!
