### ISSUE TITLE
How to disable dragging on map?

### ISSUE THREAD

**Issue by eapatel** [gnijuohz/echarts-leaflet#35]
I want to disable drag on map. Is there any way to achieve it? Thank you.

**Comment by eapatel** [comment]
Could someone please respond?

**Comment by salmanhasni** [comment]
set roam to false
```
leaflet: {
        roam: false
       }
        
```

**Comment by eapatel** [comment]
I've already resolved this issue. Anyway appreciate your response. Thanks @salmanhasni !!
