### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Radar-Lei** [gnijuohz/echarts-leaflet#5]
你好，我按照你的示例来做，经纬度是美国(国外的)的就会跑到南极去，如下图
![image](https://user-images.githubusercontent.com/29896531/33543718-01e73d4a-d913-11e7-8a4f-8ddcb27a43ea.png)

**Comment by Radar-Lei** [comment]
好像是坐标问题

**Comment by gnijuohz** [comment]
可以分享美国的那个具体的坐标嘛？如果是从google地图直接拿过来的可能需要经纬度调换一下。

https://github.com/Leaflet/Leaflet/issues/1455

> [longitude, latitude]-order: OpenLayers, MapboxGL, KML, GeoJSON, PostGIS, MongoDB, MySQL, GeoServer
> [latitude, longitude]-order: Leaflet, Google Maps API, ArangoDB.

这里用的是GeoJSON的格式，如果传入的是[lon, lat]应该没有问题。

**Comment by Radar-Lei** [comment]
感谢！发现问题了，粗心没注意把纬度输入在前了
