### ISSUE TITLE
 myChart.convertToPixel 方法不能使用么？

### ISSUE THREAD

**Issue by tangbohao37** [gnijuohz/echarts-leaflet#6]
使用 myChart.convertToPixel（'leaflet', geoCoord） 方法获取像素点时 出现错误

**Comment by gnijuohz** [comment]
确实还没有支持.等有时间我会研究下.

**Comment by caiyax** [comment]
toolbox的圈选工具得到的数据不对呢？

**Comment by gnijuohz** [comment]
@caiyax 可以开一个新的issue嘛？ 在leaflet上用圈选工具的时候难道不直接变成地图拖拽吗？
