### ISSUE TITLE
Is it possible to use it with the original echarts files

### ISSUE THREAD

**Issue by mzy2240** [gnijuohz/echarts-leaflet#7]
Great work dude!
Is it possible to use it with the original echarts files, instead of replacing the echarts files? Thanks.

**Comment by gnijuohz** [comment]
Sorry I need a little more info.
- What's your setup?
- What's the original version of echarts you were using and what's the version of replaced echarts?

**Comment by mzy2240** [comment]
I am using echarts 4.1.0 with angular 5. I haven't installed your extension, but from your document it seems that the echarts has been replaced somehow.

**Comment by mzy2240** [comment]
已经测试过了 可以和vue以及最新的echarts一起使用 这个issue可以关了 谢谢 @gnijuohz
